# this file build the dockerfile in the directory present in /backend and publishes it to google cloud run
# this file is run by the github action workflow


name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_API_KEYFILE }}
          export_default_credentials: true
          
      - name: Configure docker for GCP
        run: gcloud auth configure-docker
      - name: Build and tag Docker image
        working-directory: backend
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build --cache-from sasankmadati/bys-backend:latest -t sasankmadati/bys-backend:latest .
          docker push sasankmadati/bys-backend


      - name: Deploy to Google Cloud Run
        env:
          GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          GCLOUD_SERVICE_NAME: dropbox
          DOCKER_IMAGE: sasankmadati/bys-backend:latest
        run: |
          gcloud run deploy $GCLOUD_SERVICE_NAME --project ${{ secrets.GCLOUD_PROJECT_ID }} --image $DOCKER_IMAGE --platform managed --region asia-south1 --allow-unauthenticated --port 8000 --set-env-vars OPENAI_KEY=${{ secrets.OPENAI_KEY }},INLINE_RUNTIME_CHUNK=${{ secrets.INLINE_RUNTIME_CHUNK }},EMAIL=${{ secrets.EMAIL }},GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }}